language: cpp

env:
  - TARGET=oshchip-gcc
  - TARGET=nrf1dk-gcc
  - TARGET=nrf51822-32k-gcc
  - TARGET=st-nucleo-f401re-gcc
  - TARGET=efm32gg-stk-gcc
  
before_install:
  - sudo apt-get update && sudo apt-get install python-setuptools cmake build-essential ninja-build python-dev libffi-dev libssl-dev && sudo easy_install pip
  - cmake --version
  - sudo pip install --upgrade pip
  - sudo pip install yotta

install:
  - yotta target $TARGET

script:
  - yotta test
  - yotta build

after-success:
  if [ "$TRAVIS_BRANCH" == "release" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then 
    yotta publish
  fi
